//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANNOUNCEMENTS
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string ANNOUNCEMENT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
