//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalweb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FINALEntities : DbContext
    {
        public FINALEntities()
            : base("name=FINALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABOUT> ABOUT { get; set; }
        public virtual DbSet<ANNOUNCEMENTS> ANNOUNCEMENTS { get; set; }
        public virtual DbSet<CONTACT> CONTACT { get; set; }
        public virtual DbSet<LOGIN> LOGIN { get; set; }
        public virtual DbSet<ILIKE> ILIKE { get; set; }
        public virtual DbSet<HOWMANYPAGES> HOWMANYPAGES { get; set; }
        public virtual DbSet<BOOKSIREAD> BOOKSIREAD { get; set; }
    }
}
